name: release artifact

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "yarn"
      - name: intall deps
        run: yarn install --check-files
      - name: package
        run: yarn package
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG: $TAG"
          gh release create "$TAG" package.zip --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
